### ISSUE TITLE
Failure to add a reference back link and shadow object link

### ISSUE THREAD

**Issue by jemmiegod** [lithnet/acma#5]
Using the acma powershell cmdlets **Add-AcmaSchemaReferenceBackLink** and **Add-AcmaShadowObjectLink**  allows you to create one back link and one shadow object link, then all attempts afterwards fail with the following errors:

**Add-AcmaSchemaReferenceBackLink**
_System.InvalidOperationException: Cannot add an entity that already exists.
   at System.Data.Linq.Table`1.InsertOnSubmit(TEntity entity)
   at System.Data.Linq.Provider.DataBindingList`1.EndNew(Int32 itemIndex)
   at System.ComponentModel.BindingList`1.InsertItem(Int32 index, T item)
   at System.Data.Linq.Provider.DataBindingList`1.InsertItem(Int32 index, TEntity item)
   at System.ComponentModel.BindingList`1.AddNewCore()
   at System.Data.Linq.Provider.DataBindingList`1.AddNewCore()
   at System.ComponentModel.BindingList`1.System.ComponentModel.IBindingList.AddNew()
   at Lithnet.Acma.AcmaDatabase.CreateReferenceLink(AcmaSchemaObjectClass forwardLinkObjectClass, AcmaSchemaAttribute forwardLink, AcmaSchemaObjectClass backLinkObjectClass, AcmaS
chemaAttribute backLink, IBindingList bindingList)
   at Lithnet.Acma.AcmaDatabase.CreateReferenceLink(AcmaSchemaObjectClass forwardLinkObjectClass, AcmaSchemaAttribute forwardLink, AcmaSchemaObjectClass backLinkObjectClass, AcmaS
chemaAttribute backLink)
   at Lithnet.Acma.PS.AddAcmaSchemaReferenceBackLink.ProcessRecord()
Add-AcmaSchemaReferenceBackLink : Cannot add an entity that already exists.
At line:6 char:1
+ Add-AcmaSchemaReferenceBackLink -SourceObjectClass person -SourceAttr ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AcmaSchemaReferenceBackLink], InvalidOperationException
    + FullyQualifiedErrorId : UnknownError,Lithnet.Acma.PS.AddAcmaSchemaReferenceBackLink_

**Add-AcmaShadowObjectLink**
_System.InvalidOperationException: Cannot add an entity that already exists.
   at System.Data.Linq.Table`1.InsertOnSubmit(TEntity entity)
   at System.Data.Linq.Provider.DataBindingList`1.EndNew(Int32 itemIndex)
   at System.ComponentModel.BindingList`1.InsertItem(Int32 index, T item)
   at System.Data.Linq.Provider.DataBindingList`1.InsertItem(Int32 index, TEntity item)
   at System.ComponentModel.BindingList`1.AddNewCore()
   at System.Data.Linq.Provider.DataBindingList`1.AddNewCore()
   at System.ComponentModel.BindingList`1.System.ComponentModel.IBindingList.AddNew()
   at Lithnet.Acma.AcmaDatabase.CreateShadowLink(AcmaSchemaObjectClass shadowClass, AcmaSchemaAttribute provisioningAttribute, AcmaSchemaAttribute referenceAttribute, String name,
 IBindingList bindingList)
   at Lithnet.Acma.AcmaDatabase.CreateShadowLink(AcmaSchemaObjectClass shadowClass, AcmaSchemaAttribute provisioningAttribute, AcmaSchemaAttribute referenceAtttribute, String name
)
   at Lithnet.Acma.PS.AddAcmaShadowObjectLink.ProcessRecord()
Add-AcmaShadowObjectLink : Cannot add an entity that already exists.
At line:6 char:1
+ Add-AcmaShadowObjectLink -Name "legacyStudentLike" -ShadowObjectClass ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Add-AcmaShadowObjectLink], InvalidOperationException
    + FullyQualifiedErrorId : UnknownError,Lithnet.Acma.PS.AddAcmaShadowObjectLink_
 
Unloading the PS module and reloading does not resolve the issue.

**Comment by ryannewington** [comment]
Fixed in https://github.com/lithnet/acma/releases/tag/v1.1.6258
